### PR TITLE
add detector argument to dark_plan()

### LINKED ISSUE #15: Add detector argument to dark_plan()
Pass the detector from DarkFramePreprocessor to dark_plan().

### PR DESCRIPTION
**Pull request by jklynch**
This PR closes #15.

### CODE REVIEW

**Comment by jklynch** [comment]
Tests passed on my laptop....

**Comment by danielballan** [comment]
Hm, not sure about pinning to a specific minor Python. Elsewhere when we hit this we [upgraded numpy explicitly in the `.travis.yml`](https://github.com/bluesky/bluesky/commit/a02ebf69f2f47fc61400306b4f5fbb67fd1d812b).

**Comment by jklynch** [comment]
That doesn't seem much better than upgrading python explicitly in .travis.yml, but I'm happy to do it that way.

**Comment by danielballan** [comment]
The difference I see is that if we pin to a specific Python we have to remember to update it later, and we probably won’t.

**Pull request merged**
