### PR TITLE
MNT: Treat collect_asset_docs as a optional method of device

### PR DESCRIPTION
**Pull request by ke-zhang-rd**
For issue #27

### CODE REVIEW

**Comment by ke-zhang-rd** [comment]
Looks https://github.com/bluesky/bluesky-darkframes/pull/28 could solve CI failure.

**Comment by danielballan** [comment]
Good point. Mind merging #28?

**Comment by ke-zhang-rd** [comment]
We had a CI error in previous run
```
Warning, treated as error:
Cell printed to stderr:
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pims/image_reader.py:26: RuntimeWarning: PIMS image_reader.py could not find scikit-image. Falling back to matplotlib's imread(), which uses floats instead of integers. This may break your scripts. 
```
Based on code [here](https://github.com/soft-matter/pims/pull/281/files/c2eb15f101645d68bed8d2450f6ae4ba4cf3fd49), we could add scikit-image(included in this PR) to requirments.txt because I feel most users of bluesky-darkframe might already have `scikit-image` installed.

**Comment by danielballan** [comment]
> I feel most users of bluesky-darkframe might already have scikit-image installed.

I agree with that, but that's not sufficient reason to add scikit-image as a required dependency. (It's pretty heavy!) To suppress the warning, it would be sufficient to add scikit-image as a development dependency.

**Pull request merged**
